package storage

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"nexusdiet-proxy/internal/parser"
)

// Store wraps a PostgreSQL connection pool.
// Using pgxpool allows the handler to safely share one pool across
// concurrent requests without managing connections manually.
type Store struct {
	pool *pgxpool.Pool
}

// Visit represents a simplified row from the visits table
type Visit struct {
	Title     string `json:"title"`
	URL       string `json:"url"`
	Timestamp string `json:"timestamp"`
	Category  string `json:"category"`
}

// Constructor function
// NewStore connects to PostgreSQL and verifies the connection with a ping.
// connStr should be a standard DSN, e.g.: "postgres://nexus:nexus@localhost:5432/nexusdiet"
func NewStore(connStr string) (*Store, error) {
	pool, err := pgxpool.New(context.Background(), connStr)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection pool: %w", err)
	}

	// Verify the connection is actually reachable at startup
	if err := pool.Ping(context.Background()); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to connect to database: %w", err)
	}

	return &Store{pool: pool}, nil
}

// Close releases all connections in the pool. Should be deferred in main.
func (s *Store) Close() {
	s.pool.Close()
}

// InsertVist putter method
// InsertVisit persists a parsed article visit to the visits table.
// category is determined by the internal/classifier package before insertion.
// Note: We don't need to specify captured_at here because the database schema 
// sets "captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW()", which means Postgres 
// automatically inserts the exact time the row is saved.
func (s *Store) InsertVisit(ctx context.Context, url string, result *parser.ArticleResult, category string) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO visits (url, title, description, snippet, content, word_count, site_name, favicon, category)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	`,
		url,
		result.Title,
		result.Description,
		result.ContentSnippet,
		result.ContentClean,
		result.WordCount,
		result.SiteName,
		result.Favicon,
		category,
	)
	if err != nil {
		return fmt.Errorf("InsertVisit failed for %s: %w", url, err)
	}
	return nil
}

// GetRecentVisits getter method
// GetRecentVisits fetches the most recent articles loaded into Postgres.
// We return a simplified struct (Visit) just for the MVP dashboard list.
func (s *Store) GetRecentVisits(ctx context.Context, limit int) ([]Visit, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT captured_at, title, url, category 
		FROM visits 
		ORDER BY captured_at DESC 
		LIMIT $1
	`, limit)
	if err != nil {
		return nil, fmt.Errorf("failed to query visits: %w", err)
	}
	defer rows.Close()

	// dynamic slice (really acts like a dynamic list). "type is on the right"
	var visits []Visit
	for rows.Next() {
		var v Visit
		var t time.Time

		// We scan the timestamp generated by Postgres directly into our variables
		if err := rows.Scan(&t, &v.Title, &v.URL, &v.Category); err != nil {
			return nil, fmt.Errorf("failed to scan row: %w", err)
		}

		// Format the time as a nice string for React to display right away
		v.Timestamp = t.Format(time.RFC3339) 
		visits = append(visits, v)
	}

	if rows.Err() != nil {
		return nil, fmt.Errorf("row iteration error: %w", rows.Err())
	}

	// Return empty array instead of null for JSON serialization if no visits exist
	if visits == nil {
		visits = []Visit{}
	}

	return visits, nil
}

// Getter method for quickly returning the total amount of rows (visits) (and therfore the total sites visited count)
// GetTotalVisits returns the total count of rows in the visits table.
func (s *Store) GetTotalVisits(ctx context.Context) (int, error) {
	var count int
	err := s.pool.QueryRow(ctx, "SELECT COUNT(*) FROM visits").Scan(&count)
	return count, err
}
